site_name: Faulancer Framework
site_url: https://fkde.github.io/faulancer

theme:
  name: material

docs_dir: docs/

markdown_extensions:
  def_list: {}
  toc:
    permalink: ¶
    separator: "_"
  admonition: {}

plugins:
  - tags:
      tags_file: tags.md

nav:
  - Setup:
    - Installation: installation.md
    - Configure: initialConfiguration.md
  - Components:
    - Assets:
      - Images: components/assets/images.md
      - Style: components/assets/style.md
      - Javascript: components/assets/javascript.md
      - Icons: components/assets/icons.md
    - Commands: components/commands.md
    - Configuration: components/configuration.md
    - Controller: components/controller.md
    - Database:
      - Entities: components/database/entities.md
      - Migrations: components/database/migrations.md
      - Fixtures: components/database/fixtures.md
    - Events: components/events.md
    - Exceptions: components/exceptions.md
    - Forms:
      - Elements: components/forms/elements.md
      - Validators: components/forms/validators.md
    - Http client: components/httpClient.md
    - Initializer:
      - AwareInterface: components/awareInterface.md
    - Routing:
      - Parameters: components/routing/parameters.md
      - Validation: components/routing/constraints.md
      - Multi-language: components/routing/language.md
      - Dispatcher: components/routing/dispatcher.md
    - Templates:
      - View Helper:
        - Blocks: components/viewHelper/blocks.md
        - Link: components/viewHelper/link.md
        - Path: components/viewHelper/path.md
        - Layout: components/viewHelper/layout.md
        - Translate: components/viewHelper/translate.md
    - Translation: components/translation.md
    - Security: components/security.md
    - Session: components/session.md
  - Cookbook:
    - Define a route: cookbook/basicRoute.md
    - Create a controller: cookbook/basicController.md
    - Build a form: cookbook/basicForm.md
    - Create a service: cookbook/basicService.md
    - Make a simple request: cookbook/basicRequest.md
    - Persist data: cookbook/basicEntity.md
    - Register own command: cookbook/basicCommand.md
    - Create own form validator: cookbook/basicFormValidator.md
    - Secure your application: cookbook/basicSecurity.md