site_name: Faulancer Framework
site_url:

theme:
  name: material

docs_dir: docs/

markdown_extensions:
  def_list: {}
  toc:
    permalink: ¶
    separator: "_"
  admonition: {}

plugins:
  - tags:
      tags_file: Tags.md

nav:
  - Installation: Installation.md
  - Basic usage: Usage.md
  - Components:
    - Assets:
        - Images: Components/Assets/Images.md
        - Style: Components/Assets/Style.md
        - Javascript: Components/Assets/Javascript.md
        - Icons: Components/Assets/Icons.md
    - Controller: Components/Controller.md
    - Database:
      - Entities: Components/Database/Entities.md
      - Migrations: Components/Database/Migrations.md
      - Fixtures: Components/Database/Fixtures.md
    - Routing:
      - Parameters: Components/Routing/Parameters.md
      - Validation: Components/Routing/Constraints.md
      - Multi-Language: Components/Routing/Language.md
      - Dispatcher: Components/Routing/Dispatcher.md
    - Templates:
      - ViewHelper:
        - Blocks: Components/ViewHelper/Blocks.md
        - Link: Components/ViewHelper/Link.md
        - Path: Components/ViewHelper/Path.md
        - Layout: Components/ViewHelper/Layout.md
        - Translate: Components/ViewHelper/Translate.md
    - Forms:
      - Elements: Components/Forms/Elements.md
      - Validators: Components/Forms/Validators.md
    - Commands: Components/Commands.md
    - Configuration: Components/Configuration.md
    - Session: Components/Session.md
    - Events: Components/Events.md
    - HttpClient: Components/HttpClient.md
    - AwareInterface: Components/AwareInterface.md
    - Translation: Components/Translation.md
    - Security: Components/Security.md
    - Exceptions: Components/Exceptions.md
  - Cookbook:
    - Create a controller: Cookbook/BasicController.md
    - Build a form: Cookbook/BasicForm.md
    - Create a service: Cookbook/BasicService.md
    - Make a request: Cookbook/BasicRequest.md
    - Persist data: Cookbook/BasicEntity.md
    - Register own command: Cookbook/BasicCommand.md
    - Create own form validator: Cookbook/BasicFormValidator.md
    - Secure your application: Cookbook/BasicSecurity.md